name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main  # Ejecuta el pipeline cuando se haga un push a la rama principal

jobs:
  terraform:
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.5  # Usa la versión deseada de Terraform

      - name: Configurar AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Región que usas en Terraform

      - name: Inicializar Terraform
        run: terraform init

      - name: Planificar Terraform
        run: terraform plan

      - name: Aplicar Terraform
        run: terraform apply -auto-approve
